from module.base.button import Button
from module.base.template import Template

# This file was automatically generated by dev_tools/button_extract.py.
# Don't modify it manually.

# Kamdzy - en-US COMPLETED_1/2 recaptured from Quency's active rehab page. The
# zh-CN templates were small 30x18 icon slices tuned to specific point-tier
# colors (brown/orange, dark-purple) that don't render the same on en-US.
# Widened to the whole "✓ Complete" pill (124x36) at each of the first two
# mission rows — Row 1 20P = dark purple, Row 2 10P = teal. Other tiers
# (COMPLETED_3..6) still need recapture when a mission of that color surfaces.
COMPLETED_1 = Button(area={'zh-CN': (496, 834, 529, 852), 'en-US': (448, 822, 572, 858)}, color={'zh-CN': (106, 89, 40), 'en-US': (106, 54, 136)}, button={'zh-CN': (496, 834, 529, 852), 'en-US': (448, 822, 572, 858)}, file={'zh-CN': './assets/zh-CN/liberation/COMPLETED_1.png', 'en-US': './assets/en-US/liberation/COMPLETED_1.png'})
COMPLETED_2 = Button(area={'zh-CN': (497, 914, 526, 928), 'en-US': (448, 897, 572, 933)}, color={'zh-CN': (104, 46, 146), 'en-US': (44, 112, 138)}, button={'zh-CN': (497, 914, 526, 928), 'en-US': (448, 897, 572, 933)}, file={'zh-CN': './assets/zh-CN/liberation/COMPLETED_2.png', 'en-US': './assets/en-US/liberation/COMPLETED_2.png'})
COMPLETED_3 = Button(area={'zh-CN': (497, 991, 527, 1007), 'en-US': (497, 991, 527, 1007)}, color={'zh-CN': (27, 96, 129), 'en-US': (27, 96, 129)}, button={'zh-CN': (497, 991, 527, 1007), 'en-US': (497, 991, 527, 1007)}, file={'zh-CN': './assets/zh-CN/liberation/COMPLETED_3.png', 'en-US': './assets/zh-CN/liberation/COMPLETED_3.png'})
COMPLETED_4 = Button(area={'zh-CN': (363, 961, 398, 977), 'en-US': (363, 961, 398, 977)}, color={'zh-CN': (163, 47, 174), 'en-US': (163, 47, 174)}, button={'zh-CN': (363, 961, 398, 977), 'en-US': (363, 961, 398, 977)}, file={'zh-CN': './assets/zh-CN/liberation/COMPLETED_4.png', 'en-US': './assets/zh-CN/liberation/COMPLETED_4.png'})
COMPLETED_5 = Button(area={'zh-CN': (361, 1039, 397, 1055), 'en-US': (361, 1039, 397, 1055)}, color={'zh-CN': (60, 123, 167), 'en-US': (60, 123, 167)}, button={'zh-CN': (361, 1039, 397, 1055), 'en-US': (361, 1039, 397, 1055)}, file={'zh-CN': './assets/zh-CN/liberation/COMPLETED_5.png', 'en-US': './assets/zh-CN/liberation/COMPLETED_5.png'})
COMPLETED_6 = Button(area={'zh-CN': (363, 1115, 395, 1134), 'en-US': (363, 1115, 395, 1134)}, color={'zh-CN': (196, 128, 44), 'en-US': (196, 128, 44)}, button={'zh-CN': (363, 1115, 395, 1134), 'en-US': (363, 1115, 395, 1134)}, file={'zh-CN': './assets/zh-CN/liberation/COMPLETED_6.png', 'en-US': './assets/zh-CN/liberation/COMPLETED_6.png'})
CONFIRM_D = Button(area={'zh-CN': (330, 1141, 389, 1167), 'en-US': (330, 1141, 389, 1167)}, color={'zh-CN': (136, 137, 137), 'en-US': (136, 137, 137)}, button={'zh-CN': (330, 1141, 389, 1167), 'en-US': (330, 1141, 389, 1167)}, file={'zh-CN': './assets/zh-CN/liberation/CONFIRM_D.png', 'en-US': './assets/zh-CN/liberation/CONFIRM_D.png'})
