from module.base.button import Button
from module.base.template import Template

# This file was automatically generated by dev_tools/button_extract.py.
# Don't modify it manually.

# Kamdzy - en-US COMPLETED_1..3 are the tier-colour-agnostic "Complete" text
# bands for the three visible Daily Proxy Volunteer rows. They are matched via
# Button.match_luma (see Liberation.claim_completed): the pill colour tracks
# the point tier and reshuffles daily, so an RGB match scores by colour and
# confuses a cyan "Go" pill with a teal "Complete" one. Luma compares only
# the white glyphs. The 'color' values below are the live per-row means on the
# capture day and are informational; the luma path does not consult them.
COMPLETED_1 = Button(area={'zh-CN': (496, 834, 529, 852), 'en-US': (470, 832, 565, 853)}, color={'zh-CN': (106, 89, 40), 'en-US': (85, 75, 39)}, button={'zh-CN': (496, 834, 529, 852), 'en-US': (470, 832, 565, 853)}, file={'zh-CN': './assets/zh-CN/liberation/COMPLETED_1.png', 'en-US': './assets/en-US/liberation/COMPLETED_1.png'})
COMPLETED_2 = Button(area={'zh-CN': (497, 914, 526, 928), 'en-US': (470, 909, 565, 930)}, color={'zh-CN': (104, 46, 146), 'en-US': (29, 59, 75)}, button={'zh-CN': (497, 914, 526, 928), 'en-US': (470, 909, 565, 930)}, file={'zh-CN': './assets/zh-CN/liberation/COMPLETED_2.png', 'en-US': './assets/en-US/liberation/COMPLETED_2.png'})
COMPLETED_3 = Button(area={'zh-CN': (497, 991, 527, 1007), 'en-US': (470, 987, 565, 1008)}, color={'zh-CN': (27, 96, 129), 'en-US': (71, 35, 101)}, button={'zh-CN': (497, 991, 527, 1007), 'en-US': (470, 987, 565, 1008)}, file={'zh-CN': './assets/zh-CN/liberation/COMPLETED_3.png', 'en-US': './assets/en-US/liberation/COMPLETED_3.png'})
COMPLETED_4 = Button(area={'zh-CN': (363, 961, 398, 977), 'en-US': (363, 961, 398, 977)}, color={'zh-CN': (163, 47, 174), 'en-US': (163, 47, 174)}, button={'zh-CN': (363, 961, 398, 977), 'en-US': (363, 961, 398, 977)}, file={'zh-CN': './assets/zh-CN/liberation/COMPLETED_4.png', 'en-US': './assets/zh-CN/liberation/COMPLETED_4.png'})
COMPLETED_5 = Button(area={'zh-CN': (361, 1039, 397, 1055), 'en-US': (361, 1039, 397, 1055)}, color={'zh-CN': (60, 123, 167), 'en-US': (60, 123, 167)}, button={'zh-CN': (361, 1039, 397, 1055), 'en-US': (361, 1039, 397, 1055)}, file={'zh-CN': './assets/zh-CN/liberation/COMPLETED_5.png', 'en-US': './assets/zh-CN/liberation/COMPLETED_5.png'})
COMPLETED_6 = Button(area={'zh-CN': (363, 1115, 395, 1134), 'en-US': (363, 1115, 395, 1134)}, color={'zh-CN': (196, 128, 44), 'en-US': (196, 128, 44)}, button={'zh-CN': (363, 1115, 395, 1134), 'en-US': (363, 1115, 395, 1134)}, file={'zh-CN': './assets/zh-CN/liberation/COMPLETED_6.png', 'en-US': './assets/zh-CN/liberation/COMPLETED_6.png'})
CONFIRM_D = Button(area={'zh-CN': (330, 1141, 389, 1167), 'en-US': (330, 1141, 389, 1167)}, color={'zh-CN': (136, 137, 137), 'en-US': (136, 137, 137)}, button={'zh-CN': (330, 1141, 389, 1167), 'en-US': (330, 1141, 389, 1167)}, file={'zh-CN': './assets/zh-CN/liberation/CONFIRM_D.png', 'en-US': './assets/zh-CN/liberation/CONFIRM_D.png'})
